### ISSUE TITLE
#b32d27b Reverse it again... Kinda (tmysql 4 abandoned)

### ISSUE THREAD

**Issue by MomoxStudios** [FPtje/darkrpmodification#102]
I was the one suggesting to use tmysql4 instead of mysqloo (which had a big memory leak back then). So this time tmysl4 has been abandoned ([Proof](https://facepunch.com/showthread.php?t=1442438)). I'd recommend mysqloo v9.3 now [Link](https://facepunch.com/showthread.php?t=1515853).
Thanks in advice.

**Comment by strideynet** [comment]
Are you suggesting to change the default? As far as I'm aware DarkRP already has support for both through  Falco's MySQLite module.

**Comment by MomoxStudios** [comment]
No, I talked about reversing #b32d27b (changing the text in the MySQL config file telling you to download tmysql4)
