### ISSUE TITLE
Language strings, bug and repeating of unanswered question. 

### ISSUE THREAD

**Issue by Satton2** [FPtje/darkrpmodification#120]
### Spawn positions

![1](https://user-images.githubusercontent.com/23385240/38693106-9c521112-3e8e-11e8-9311-ed89cdb3a35e.gif)
As you can see strings are mixed up. And it would be nice to change them to:
**/addspawn** → You have added a spawn position for %s. 
**/setspawn** →  You have removed all spawn positions for %s and added a new one here. 
**/removespawn** → You have removed all spawn positions for %s.
_¹_ — [Pull request (language file only)](https://github.com/FPtje/darkrpmodification/pull/119).
### Shipments

1. 

![image](https://user-images.githubusercontent.com/23385240/38695309-995b2060-3e94-11e8-89a0-4a63669777c6.png)

2. 

![image](https://user-images.githubusercontent.com/23385240/38695338-aa56daf8-3e94-11e8-9616-4b4d6cc9bf4b.png)

Can you add this strings into the language file?

## Bug
If we will set this function to false:
![image](https://user-images.githubusercontent.com/23385240/38694766-2a4c22ec-3e93-11e8-9589-9299ba76a31c.png)
and then die we will get this error message:

```
[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:421: attempt to perform arithmetic on field 'LastJailed' (a nil value)
  1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:421
```

And if will slay ourself by using /slay command we will get this error:

```
[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:421: attempt to perform arithmetic on field 'LastJailed' (a nil value)
  1. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:421
   2. Kill - [C]:-1
    3. callback - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/playeractions/slay/sv_init.lua:15
     4. v - gamemodes/darkrp/gamemode/modules/fadmin/fadmin/commands/sv_chatcommands.lua:30
      5. unknown - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:139
```
## About my translation (because it was unanswered earlier)

As you already know, I am working on Russian translation for DarkRP. So, when I will finish the work, can I make a pull request with my localization file (or propose it like new file) to make it official?

**Comment by FPtje** [comment]
I'd rather have no new languages in the DarkRPMod. You can add the language as an addon, that would probably be better.

**Comment by mcNuggets1** [comment]
Createshipment and splitshipment translations should be in darkrp already, if you ask me, but the jail position changes arent needed

**Comment by Satton2** [comment]
@FPtje Okay.
@mcNuggets1 Am I said something about jail positions? =)

**Comment by mcNuggets1** [comment]
I meant spawn position strings, sorry, just woke up there.

**Comment by FPtje** [comment]
fixed
