### ISSUE TITLE
Jobs are not showing in Arvia F4 Menu

### ISSUE THREAD

**Issue by detroitnigga6** [FPtje/darkrpmodification#123]
HELP!I have a real´ big Problem:I wanna have a MilizrayRP Server and I downloaded darkrpmodification-master&Arivia F4 Menu.I put darkrpmod.&arivia in my addons folder and arrivia in my addons folder,I restart the du*mp Server,but arivia show me only 4 Weapon´s in the Weapon folder&only the custom jobs and no other custom Shipments.Here for example a job&shipment:

})
TEAM_UAC=DarkRP.createJob("US Army Recrut"),{
color=(31,211,172,255),
model="models/Humans/corpse1.mdl",
description = [[Als US Army Recrut hast du dich entschieden,der Army zu dienen.Du bist respektvoll und willst was lernen.]],
weapon={"","cw_m1911"},
command="obdachloser",
max=0,
salary=9000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
admin=0,
vote=false,
hasLicense=true,
candemote=true,
category="US Army",
})
Or is there a problem with the f4 menu

**Comment by FPtje** [comment]
Not a help forum
