### ISSUE TITLE
darkrpmodifcation not working

### ISSUE THREAD

**Issue by detroitnigga6** [FPtje/darkrpmodification#124]
HELP!I have a real´ big Problem:I wanna have a MilizrayRP Server and I downloaded darkrpmodification-master&Arivia F4 Menu.I put darkrpmod.&arivia in my addons folder and arrivia in my addons folder,I restart the du*mp Server,but arivia show me only the default jobs/shipments!

The only erorr:
[ERROR] lua/autorun/cl_hud.lua:68: attempt to perform arithmetic on field 'Energy' (a nil value)
  1. v - lua/autorun/cl_hud.lua:68
   2. unknown - lua/includes/modules/hook.lua:84

**Comment by detroitnigga6** [comment]
Here is one job for example:

TEAM_T = DarkRP.createJob("Test", {
    color = Color(130, 62, 62, 255),
    model = {"models/player/breen.mdl"},
    description = [[LULU]],
    weapons = {"cw_ak47"},
    command = "ilove",
    max = 2,
    salary = 260,
    admin = 0,
    vote = true,
    hasLicense = true,
    candemote = true
})

**Comment by FPtje** [comment]
Not a help forum
