### ISSUE TITLE
GM:GodEnable/Disable() causes script errors when executed in DarkRP-Jobs "OnPlayerChangedTeam" function

### ISSUE THREAD

**Issue by Quantum2707** [FPtje/darkrpmodification#131]
When giving the player god by changing team it works but it throws an error like following

[ERROR] addons/darkrpmodification/lua/darkrp_customthings/jobs.lua:254: attempt to call method 'GodEnable' (a nil value)
  1. OnPlayerChangedTeam - addons/darkrpmodification/lua/darkrp_customthings/jobs.lua:254
   2. Call - gamemodes/darkrp/gamemode/modules/base/sh_gamemode_functions.lua:18
    3. Function - gamemodes/darkrp/gamemode/modules/base/cl_gamemode_functions.lua:78
     4. unknown - lua/includes/modules/usermessage.lua:87

My code:
`
OnPlayerChangedTeam = function(ply, oldTeam, newTeam)
        ply:GodEnable()
    end,
`

`
OnPlayerChangedTeam = function(ply, oldTeam, newTeam)
        if oldTeam == TEAM_TM then
            ply:GodDisable()
        end
    end,
`

Does not seem like a own coding error because OnPlayerChangedTeam expected no value for this function call and GM:GodEnable() and GM:GodDisable() is available.

**Comment by FPtje** [comment]
`OnPlayerChangedTeam = function(ply, oldTeam, newTeam) if SERVER then ply:GodEnable() end end,`

Also, not a help forum. Go to forum.darkrp.com

**Comment by Quantum2707** [comment]
Thanks a lot!

I am sorry Falco, did not think about having the possibility to have SERVER nil.
