### ISSUE TITLE
GM.Config.maxlawboards doesn't work

### ISSUE THREAD

**Issue by Potatosayno** [FPtje/darkrpmodification#137]
### Description of the bug
-- In the DarkRP modification settings.lua when trying to change GM.Config.maxlawboards to lets say 2, you are able to spawn 7.
I have it set on 2, and Mayor's are still able to spawn 7 of these (Yes, I did double check it was on 2, and I even went far enough to test it on my private server).

### How to make the bug happen
-- Simply change GM.Config.maxlawboards in Settings.lua to 2 (I haven't tested other values) and you still should be able to spawn 7 lawboards.

### Lua errors
-- None

### Why the developer of DarkRP is responsible for this issue
-- This is an issue with darkrpmodification, and this script has been made by the DarkRP developer.

**Comment by FPtje** [comment]
Actually, 2 is the default maximum for lawboards. I'm not sure what you're getting it from, but I'm hitting the limit when trying to spawn the third lawboard.
![hl2_2019-04-14_11-33-28](https://user-images.githubusercontent.com/1202014/56090975-36008b00-5ea9-11e9-9e4e-87ce245deb17.png)


When changing the limit, DarkRP changes accordingly, though after a changelevel.

**Comment by FPtje** [comment]
The most likely cause of this issue is that you have some other Lua script setting it to 7.
