### ISSUE TITLE
Setting disallowClientsideScripts to true messes up the entire gamemode

### ISSUE THREAD

**Issue by lRoberth** [FPtje/darkrpmodification#139]
If i set disallowClientside to true, everything stops working, no chat, no F4, no HUD, no Q spawn menu, nothing, and then Cake Anticheat kicks you for Truth Engineering (2) 15 seconds later.

**Comment by Jophes** [comment]
The spawn menu is a client side script, you disabled client side scripts, I'm not sure what you were expecting to happen

**Comment by lRoberth** [comment]
This never happened before till one of the updates, then how am I going to stop cheaters loading their .lua cheats?, Cake Anticheat doesn't do anything if this value is set to false

**Comment by Jophes** [comment]
Ah, my bad, I had assumed you were setting this in gmod somewhere. Is this an option in the anti cheat addon?
If it is try it trouble in terrorist town or something and see if it still breaks as it sounds like an issue with the anticheat.
If I remember correctly when you enable that you need to whitelist what scripts you still want to work or some thing like that

**Comment by lRoberth** [comment]
This is darkrpmodification addon, that's the reason why I'm posting this as issue in here.
It's all either GMod, DarkRP or this addon fault.
There's no way to whitelist stuff.

**Comment by lRoberth** [comment]
If you didn't know, that options forces sv_allowcslua to 1, no matter if you try to change it later.
And as you can see in this screenshot, Cake Anticheat will ignore all cheaters when they load in their cheat.

https://i.imgur.com/kBTTfe4.png

**Comment by lRoberth** [comment]
I've discovered that if you even manually set sv_allowcslua to 0, next users that join the server the server would be broken for them, but setting it back to sv_allowcslua 1 and tell users to rejoin, everything would be fixen

**Comment by FPtje** [comment]
I'm afraid the issue here lies with cac. IIRC, cac needs to register which functions are good, and which aren't.  Updates tend to change those things, causing cac to think you're cheating.

The solution probably lies with updating cac. I cannot reproduce the issue, as I don't have cac.
