### ISSUE TITLE
how do i disable civil protection in your darkrp server

### ISSUE THREAD

**Issue by benthegamingguy09** [FPtje/darkrpmodification#140]
So i'm trying to disable civil protection "not the class but the category" so im not sure how to explain this but when i go into my darkrp darkrpmodification-master and then lua and then darkrp-config its not in there 

So if anyone could help me on this that would be amazing
    Thanks
:)

**Comment by Jophes** [comment]
You want 'darkrp_customthings', not config.
For future reference, this isn't a help forum.

**Comment by benthegamingguy09** [comment]
Im not looking for help im looking to solve my issue and thats what this site is. Btw i went to where you said to go and maybe where do i go to disable the category?

**Comment by Bo98** [comment]
> Im not looking for help

> So if anyone could help me on this that would be amazing

This place is for reporting bugs or requesting features.

You're probably looking for GM.Config.CategoryOverride btw.

**Comment by Jophes** [comment]
^ that's in darkrp_config/settings.lua fyi
I was wrong in saying darkrp_customthings
