### ISSUE TITLE
Buying custom entities with 0 limit will show the "You have reached the X limit!" error.

### ISSUE THREAD

**Issue by Famous5000** [FPtje/darkrpmodification#141]
Related to #16, re-opened because it's happening again. Trying to buy a custom entity and once I try to that happens. There are only 4 different entities that I can buy, all of the entities have no limits.

**Comment by Famous5000** [comment]
Should note that the entities had no limit before and they worked just fine. Not sure what caused the bug.

**Comment by Famous5000** [comment]
Apparently having extra groups/shipments in the entities.lua file causes the issue. Would love a way to buy a large amount of an entity without having to have it separate in the shipments tab as well...

**Comment by Bo98** [comment]
By "0 limit" do you mean setting "max = 0"? I'm not sure if that ever worked.

**Comment by Famous5000** [comment]
Yes, I do. Sorry for being unclear about that.

**Comment by FPtje** [comment]
Fixed in https://github.com/FPtje/DarkRP/commit/92195cef39d559fb13145f3c873ff0a66f3bda40

**Comment by Bo98** [comment]
I'll add a mention of this on the wiki too.
