### ISSUE TITLE
AFK module working incorrectly.

### ISSUE THREAD

**Issue by yoitsej** [FPtje/darkrpmodification#144]
Hello, the AFK module is working incorrectly. The part that is working incorrectly is it doesn't display 'AFK' for your job on the scoreboard when you're AFK.

**Comment by FPtje** [comment]
![hl2_2019-09-29_13-36-59](https://user-images.githubusercontent.com/1202014/65831881-4a510c80-e2be-11e9-90a0-4dbcc98bb459.png)

Works for me

**Comment by yoitsej** [comment]
Could it be caused by the scoreboard I’m using then?

**Comment by FPtje** [comment]
Yes, of course
