### ISSUE TITLE
Keep getting this issue and im not sure why

### ISSUE THREAD

**Issue by FBFezz** [FPtje/darkrpmodification#146]
[ERROR] gamemodes/policerp/gamemode/modules/base/sv_gamemode_functions.lua:811: bad argument #1 to 'Give' (string expected, got boolean)
  1. Give - [C]:-1
   2. Call - gamemodes/policerp/gamemode/modules/base/sv_gamemode_functions.lua:811
    3. unknown - gamemodes/policerp/gamemode/modules/base/sv_gamemode_functions.lua:766

I keep getting this issue and im not sure why

**Comment by FPtje** [comment]
> policerp

You edited core files. That's the point where I drop any and all support. 

https://corefiles.darkrp.eu/

**Comment by FPtje** [comment]
There are enough text files in the repository telling you not to do precisely that.

**Comment by FBFezz** [comment]
[ERROR] gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:811: bad argument #1 to 'Give' (string expected, got boolean)
  1. Give - [C]:-1
   2. Call - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:811
    3. unknown - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:766

**Comment by FBFezz** [comment]
I think its my modification data anyway but everything looks in order

**Comment by FPtje** [comment]
You put a boolean in `GAMEMODE.Config.DefaultWeapons`. That's a type error in your config.

**Comment by FBFezz** [comment]
Thank you, but one more question, is there a way to class darkrp as another gamemode in the server browser?

**Comment by FPtje** [comment]
Yes:
https://github.com/FPtje/DarkRP/releases/tag/derived

**Comment by FBFezz** [comment]
Ahh thanks for the support
