### ISSUE TITLE
darkrp data not writing to database.

### ISSUE THREAD

**Issue by deadspidervenom** [FPtje/darkrpmodification#148]
So we recently had to delete our sv.db due one of our staff giving us a "payed addon", we found out quickly it was not.

When that happened it "wiped" our sv,db, and sense then it seems like darkrp (as well as FPP) are having issues writing to a database. Darkrp can save group doors, and doors assigned to jobs.

However it can not seem to save disallowing ownership to a door after a restart(for FPP its blacklisting xd).

We have tried deleting sv.db to regen it, we even tried setting up mysql, nothing is letting us save disallowing door ownership. I was curious if you knew the cause, or if this was a bug with darkrp.

**Comment by FPtje** [comment]
Not a help forum. Go to forum.darkrp.com

**Comment by FPtje** [comment]
This definitely does not look like a DarkRP bug
