### ISSUE TITLE
setBodygroup doesn't change anything

### ISSUE THREAD

**Issue by Lame-Game** [FPtje/darkrpmodification#154]
I have a StarWarsRP server based on darkrp.
This is on Job:
TEAM_NTPVT = DarkRP.createJob("NTPVT", { -- Name
    color = Color(255, 247, 0, 255), -- Team color
    model = "models/player/hydro/novatrooper/novatrooper.mdl", -- Player model
    description = [[Become a Nova Trooper, NT reg' is an elite regiment]],  -- Job description
    weapons = {"weapon_752bf3_dlt19", "weapon_752bf3_dl44","keys","weapon_752bf3_binoculars","stunstick","weapon_cuff_elastic","taser","arrest_stick","unarrest_stick"}, -- Additional weapons
    command = "ntpvt", -- Command to become the job
    max = 8, -- Maximum amount of said job
    salary = 58, -- Salary
    admin = 0, -- Requires Admin? 1 for yes, 0 for no.
    vote = false, -- Do they need to vote? true for yes, false for no.
    sortOrder = 40;
	category = "NovaTroopers",
	PlayerSpawn = function(ply) ply:SetHealth(100) ply:SetGravity(1) **ply:SetBodygroup(0, 1) ply:SetBodygroup(1, 1)** return CLIENT end,
	hasLicense = true, -- Has a license
	customCheck = function(ply) return CLIENT or ply:IsUserGroup("NTPVT") or ply:IsAdmin() or ply:IsSuperAdmin() or ply:IsUserGroup("JUDGE") or ply:IsUserGroup("Event Manager") end,
		CustomCheckFailMsg = "This job is not for your group!"
})

The Fat one is the Bodygroup, but ingame the bodygroup wont change, how can I fix this?

**Comment by FPtje** [comment]
This is not a help forum.

You can try `timer.Simple(0, function() ply:SetBodygroup(1, 1) end)`, but if that doesn't work it's probably best to ask on the DarkRP discord.
