### ISSUE TITLE
customcheck not works

### ISSUE THREAD

**Issue by SuchtClub** [FPtje/darkrpmodification#155]
Is not works
When i write on Shipments.lua this code here

```
DarkRP.createShipment("Messer", {
	model = "models/weapons/w_extreme_ratio.mdl",
	entity = "m9k_knife",
	price = 5000,
	amount = 3,
	seperate = true,
	pricesep = 5000,
	noship = false,
	allowed = {TEAM_GUN},
	category = "Nahkampf"
})
```

Can a Citizen Buy the Weapon and the Job is created to TEAM_GUN

```
TEAM_GUN = DarkRP.createJob("Waffenhändler", {
	color = Color(255, 140, 0, 255),
	model = "models/player/monk.mdl",
	description = [[Der Waffenhändler verkauft Waffen von groß bis klein an die Stadt.]],
	weapons = {},
	command = "waffenhändler",
	max = 2,
	salary = 200,
	admin = 0,
	vote = false,
	hasLicense = false,
	category = "Verkäufer",
	sortOrder = 4,
	customCheck = function(ply)
		return MRP_DonatorGroups[ply:GetUserGroup()] or ply:IsAdmin() or ply.GetUTimeTotalTime and ply:GetUTimeTotalTime() >= 1800 
	end,
	CustomCheckFailMsg = function(ply)
	 	return "Du benötigst mindestens eine halbe Stunde Spielzeit, um diesen Job ausüben zu können!"
	end
})
```

**Comment by SuchtClub** [comment]
> Is not works
> When i write on Shipments.lua this code here
> DarkRP.createShipment("Desert eagle", {
> model = "models/weapons/w_pist_deagle.mdl",
> entity = "weapon_deagle2",
> price = 215,
> amount = 10,
> separate = true,
> pricesep = 215,
> noship = true,
> **allowed = {TEAM_GUN},**
> category = "Pistols",
> })
> 
> Can a Citizen Buy the Weapon and the Job is created to TEAM_GUN
> 
`TEAM_GUN = DarkRP.createJob("Waffenhändler", {
> color = Color(20, 150, 20, 255),
> model = {
> "models/player/group01/female_01.mdl",
> 
 },
> description = [[Du bist ein Waffenhändler]],
> weapons = {},
> command = "whandel",
> max = 0,
> salary = 80,
> admin = 0,
> vote = false,
> hasLicense = false,
> candemote = false,
> category = "Neutral",
> sortOrder = 1,
> ```
> 
> })`

**Comment by FPtje** [comment]
This is not a help forum.

**Comment by SuchtClub** [comment]
ah and the under people help you Right !
