### ISSUE TITLE
editing files

### ISSUE THREAD

**Issue by speege** [FPtje/darkrpmodification#159]
i tried editing the jobs menu by adding code ie 
TEAM_SADMIN = DarkRP.createJob("SuperAdmin On Duty", {

   color = Color(150, 20, 20, 255),

   model = "models/player/zeus_combine_v2/zeus_combine_v2.mdl",

   description = [[]],

   weapons = {},

   command = "saod",

   max = 0,

   salary = 100,

   admin = 0,

   vote = false,

   hasLicense = false,

   customCheck = function(ply) return ply:GetUserGroup() == "superadmin" end,

 

})

but nothing ever actually changes in darkrp.

**Comment by FPtje** [comment]
Please ask on the darkrp discord. This issue tracker is for bugs and feature requests, not for help and support.
