### ISSUE TITLE
Custom things aren't working

### ISSUE THREAD

**Issue by Excersu** [FPtje/darkrpmodification#162]
So I reinstalled DarkRP and DarkRP Custom Things twice. DarkRP works great and just fine. Thing is, in the modification folder, where it has custom things. NOTHING and I mean NOTHING will work there. Jobs, Shipments, Categories.. they will not work. I've contacted other people and some support pages but they said everything looks fine. So I'm not sure what to do. I even ran it through the code tester on here and it says everything is fine. I even tried copying and pasting from Job and Shipment and Category generator websites. What can I do?

**Comment by FlorianLeChat** [comment]
You are more likely to find help on the [DarkRP Discord](https://darkrp.page.link/discord) than here since this is not a technical problem but a configuration problem.

**Comment by Excersu** [comment]
Yeah I tried talking to them and they kind of just made fun of it so I don't know what to do

**Comment by FPtje** [comment]
Probably not installed correctly. This is not for help though.

**Comment by Excersu** [comment]
It is installed correctly though. Is their anything that you could do to
maybe help me figure it out then? Cause I've watched video after video and
I have done the same thing they are doing. This is really bugging me and
taking money from me for the server hosting
