### ISSUE TITLE
DarkRP, HUD, F4, Scoreboard, Gray Playermodel issue

### ISSUE THREAD

**Issue by Aresuvn** [FPtje/darkrpmodification#166]
Hi, I'm sorry if I'm bothering you but I really need help with my DarkRP server. The point is, when I go to the server my character is completely gray model without any animations. Also, when I open the scoreboard, it shows my user with the work "Unnasigned". When I open F4, I can't change my job because I get the error "Your data has not been loaded yet" and "If this persists, try rejoining or contacting an admin". On my hud the job just doesn't show "Job: -". I am a novice server owner, so please be understanding. I reinstalled DarkRP-master and darkrpmodification-master and ulx system, but it didn't help. Thanks in advance

**Comment by FlorianLeChat** [comment]
This is not the right place to get help, you might try the DarkRP Discord: https://darkrp.page.link/discord
