### ISSUE TITLE
Some translation strings are not working

### ISSUE THREAD

**Issue by jordanamr** [FPtje/darkrpmodification#167]
Hello !
So I am using darkrpmodification to translate the strings to French.
However, some strings refuse to be translated for some reason.
These strings are not being translated :
```
payday_message
hes_arrested
hes_unarrested
```

Everything else works prefectly (SWEP translation using the sh_weaponsettings file, all other i18n strings...)
I've checked the DarkRP source code but the call to the translation key is correct.
I've also ran the `darkrp_getphrases "fr"` command in console but everything seems to be translated according to the command (No language strings missing!)
I am using the latest versions of both DarkRP and darkrpmodification (the "Download zip" button, not the release)
I've linked my french.lua file in a zip to that issue.

Thanks in advance :)

[french.zip](https://github.com/FPtje/darkrpmodification/files/8665225/french.zip)

**Comment by FlorianLeChat** [comment]
I just installed an updated version of DarkRP gamemode with the darkrpmodification addon and it seems everything works on my end. Do you think it would be an addon which can clash with the gamemode?

**Comment by jordanamr** [comment]
> I just installed an updated version of DarkRP gamemode with the darkrpmodification addon and it seems everything works on my end. Do you think it would be an addon which can clash with the gamemode?

I did some more tests and it seems like the gmod_language convar is never updated...
I also tried on a blank server with no addons or custom gamemodes on both windows & linux, am I doing something wrong ?

In my garrysmod/cfg/server.cfg :
`gmod_language "fr"`

I also tried setting it when starting the server via +gmod_language "fr"

What's even more weird is that setting the convar in the console also does not work...
![image](https://user-images.githubusercontent.com/55905781/167927032-3be8bda4-4269-420f-9046-911fc6082a63.png)

**Comment by FlorianLeChat** [comment]
I have seen several people like you in the past having the same issue. I experienced this issue myself a few months ago when I was testing things on a Linux development server (under Debian 11). You could open an issue [here](https://github.com/Facepunch/garrysmod-issues/) to report it to Rubat.

**Comment by jordanamr** [comment]
> I have seen several people like you in the past having the same issue. I experienced this issue myself a few months ago when I was testing things on a Linux development server (under Debian 11). You could open an issue [here](https://github.com/Facepunch/garrysmod-issues/) to report it to Rubat.

I did it, thanks.
For anyone else, a workaround is to register your language like this :
`DarkRP.addLanguage("", french_language)`

**Comment by jordanamr** [comment]
> Do I understand correctly that the convar just doesn't work?
> 

Exactly!
And yeah, that's a nasty one :(

**Comment by FPtje** [comment]
In that case I'll close the issue. I hope you'll find a good solution besides the workaround.
