### ISSUE TITLE
I think i'm going insane over this.

### ISSUE THREAD

**Issue by IceVikings1** [FPtje/darkrpmodification#169]
I've been trying to setup custom entities and weapon shipments via darkrpmodification and it don't seem to work. But still the custom jobs work perfectly fine. And no i dont have any issues with M9K or any mods for the entities period. I'm really tired at this point and no-one i've reached out to has any concrete tips. So if falco sees this please. Help me goddamnit.

**Comment by FPtje** [comment]
For help there's the DarkRP discord. I've decided a long time ago that helping people customizer DarkRP is not a level of support I'm willing to give. I hope you'll find help there.
