### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by hellper009** [FPtje/darkrpmodification#170]
[ERROR] gamemodes/darkrp/gamemode/libraries/simplerr.lua:528: [ERROR] A runtime error has occurred in "addons/darkrpmodification-master/lua/darkrp_customthings/jobs.lua" on line 30.
The best help I can give you is this:

A table is being indexed by something that does not exist (table index is nil).

Hints:
        - The thing between square brackets does not exist (is nil).

The responsibility for the error above lies with (the authors of) one (or more) of these files:
        1. addons/darkrpmodification-master/lua/darkrp_customthings/jobs.lua on line 30
        2. gamemodes/darkrp/gamemode/libraries/fn.lua on line 84
        3. gamemodes/darkrp/gamemode/libraries/fn.lua on line 84
        4. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 138
        5. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 149
        6. gamemodes/darkrp/gamemode/init.lua on line 112
------- End of Simplerr error -------

  1. error - [C]:-1
   2. doInclude - gamemodes/darkrp/gamemode/libraries/simplerr.lua:528
    3. loadCustomDarkRPIteCouldn't Load Init Script: 'darkrp/gamemode/init.lua'

My jobs.lua
--[[---------------------------------------------------------------------------
DarkRP custom jobs
---------------------------------------------------------------------------
This file contains your custom jobs.
This file should also contain jobs from DarkRP that you edited.

Note: If you want to edit a default DarkRP job, first disable it in darkrp_config/disabled_defaults.lua
      Once you've done that, copy and paste the job to this file and edit it.

The default jobs can be found here:
https://github.com/FPtje/DarkRP/blob/master/gamemode/config/jobrelated.lua

For examples and explanation please visit this wiki page:
https://darkrp.miraheze.org/wiki/DarkRP:CustomJobFields

Add your custom jobs under the following line:
---------------------------------------------------------------------------]]

--[[---------------------------------------------------------------------------
Define which team joining players spawn into and what team you change to if demoted
---------------------------------------------------------------------------]]
GAMEMODE.DefaultTeam = TEAM_CITIZEN
--[[---------------------------------------------------------------------------
Define which teams belong to civil protection
Civil protection can set warrants, make people wanted and do some other police related things
---------------------------------------------------------------------------]]
GAMEMODE.CivilProtection = {
    [TEAM_POLICE] = true,
    [TEAM_CHIEF] = true,
    [TEAM_MAYOR] = true,
}
--[[---------------------------------------------------------------------------
Jobs that are hitmen (enables the hitman menu)
---------------------------------------------------------------------------]]
DarkRP.addHitmanTeam(TEAM_MOB)

**Comment by FPtje** [comment]
See error for what to do.
