### ISSUE TITLE
language change

### ISSUE THREAD

**Issue by nutellabrot2** [FPtje/darkrpmodification#177]
Hi,
how do i change the language of my server?
i already have put the German translation to the languages folder but everthing is still english?

**Comment by FPtje** [comment]
I believe you set it in the settings. Please look there as I don't have them at hand right now.

**Comment by FPtje** [comment]
Issue closed but you c can still respond.

**Comment by nutellabrot2** [comment]
were in the settings?

**Comment by FPtje** [comment]
Yeah those are the ones I don't have at hand because I'm on my phone. Basically there should be a language setting somewhere in the darkrpmod. IIRC you can set it to a language code like "en", "de" or whatever.

**Comment by nutellabrot2** [comment]
ok ill have a look again, but if you at your computer again could you look again? maybe you find it

**Comment by FPtje** [comment]
Oh it's here in the English.lua file:


= Using a language =
Make sure the convar gmod_language is set to your language code. You can do that in a server CFG file.

**Comment by nutellabrot2** [comment]
whats the exact code that i need to put in?

**Comment by FPtje** [comment]
Just gmod_language de in your server.cfg file?

I don't know, I haven't hosted a gmod server for probably over a decade lol.
