### ISSUE TITLE
Darkrpmodification isnt fully loading

### ISSUE THREAD

**Issue by jonas13362** [FPtje/darkrpmodification#49]
Hello ,

After extracting darkrpmodification i restarted my server ,
Then i join the server and i see the script isnt working ,
there arent any errors about darkrpmodification.
I tried to reinstall it but didnt work.
I tried adding a job with tcb creator but didnt work

Only thing i found is :
Adding Filesystem Addon 'c:\services\ni415681_1\gmod13\garrysmod\addons\darkrpmodification'
If u wanna see my full logg its here :
http://pastebin.com/u4skkN52

Thanks already ,
Jonas

**Comment by FPtje** [comment]
Works fine for me.
