### ISSUE TITLE
Modifications don't seem to load.

### ISSUE THREAD

**Issue by Fortune117** [FPtje/darkrpmodification#53]
The issue is pretty much as the title says. After adding stuff to the files in the modmaster, nothing seems to be loaded when the server is started up. No custom entities, shipments, jobs, huds, nothing. However, if I go into the settings.lua and view/edit it with filezilla and reload it, DarkRP gets refreshed and the settings are applied. Once I have done this, I also discovered that if I repeat the process with any of the other customizable files, they get loaded. However this only works if I update the settings file first. 

I've tried reinstalling the mod master and with a fresh install of DarkRP. Nothing seems to work :/

**Comment by FPtje** [comment]
Well I've barely touched the darkrpmod and it seems to work for everyone else... 
I'm going to assume it's your error and with that I'm going to refer you to the forums: forum.darkrp.com
