### ISSUE TITLE
load behaviour

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/darkrpmodification#54]
I would suggest to let the system load darkrpmodification/darkrp_config and darkrp_customthings first, as I only get trouble with other scripts as they usually load before and then can't find value 'X'.

**Comment by deinemudda32** [comment]
oh by the way the language file seems not to load correctly, on fresh restart of my server, the half of the translated file is not in the server, after a mapchange everything is translated.

**Comment by FPtje** [comment]
Use hooks.
Also how can *half* a file not be in the server!?

**Comment by FPtje** [comment]
Config files and custom things load later because the module creator can then do stuff before they are loaded. Using hooks the module creator can delay calculation until after the custom shit is loaded. This gives the module creator choice. Loading the modules after the config files would remove that choice since you can't go back in time in Lua. 

Also I just tested the language file thing and it works fine for me.

**Comment by deinemudda32** [comment]
the half of the translation is just not loaded.
Only If I change the map.
I looked into it, and only the clientside stuff works and the serverside didnt load.

**Comment by deinemudda32** [comment]
an Example is the voterestrictions.lua.
If you drag a custom job into it, it stops working and you get a neat lua error.
It just do conflicts with config files. some aren't working anymore.

**Comment by FPtje** [comment]
![2015-01-28_21-06-53](https://cloud.githubusercontent.com/assets/1202014/5945956/794b70ec-a732-11e4-9771-120a366328c9.png)
![2015-01-28_21-10-59](https://cloud.githubusercontent.com/assets/1202014/5945958/7af65588-a732-11e4-86e6-320905667c85.png)

Both serverside and clientside stuff works for me when translating. Also, the voterestrictions thing was broken anyway, it used a hook that didn't exist.

**Comment by deinemudda32** [comment]
Hm, How about a function that checks if darkrp has loaded and runs then the script.
I don't know but it keep breaking things, and I checked darkrp language again and the error seems to happen only on darkrp.Notify functions.

**Comment by deinemudda32** [comment]
Hm, how should I fix these scripts, which loads too fast?

**Comment by FPtje** [comment]
Use http://wiki.garrysmod.com/page/GM/OnGamemodeLoaded

**Comment by deinemudda32** [comment]
Im really sorry for releasing dumb thread shit :)
I found out 1 minute ago, there is a hook for it
http://wiki.darkrp.com/index.php/Hooks/server/loadcustomdarkrpitems.

I'm really sorry :package:
