### ISSUE TITLE
Translation - Linux

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/darkrpmodification#61]
I tested the language files multiple times.
In singleplayer and booth dedicated server, my custom translation works.
but however on my linux dedicated server it doesnt work. It needs a mapchange to fully work.

**Comment by FPtje** [comment]
It's that way everywhere. Deal with it.

**Comment by deinemudda32** [comment]
Isnt there a fix for this?

**Comment by FPtje** [comment]
What's wrong with changeleveling to make changes permanent?

**Comment by Bo98** [comment]
Facepunch/garrysmod-requests#71.

**Comment by deinemudda32** [comment]
I didnt mean that.
I didnt change anything while the server was online.
I restarted it to take effect. 
But It only works on map changing, even If I dragged the file before the restart in the folder.
That was what I meant.
