### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/darkrpmodification#62]
So as everyone misunderstood me in the latest issue, I will just upload some screenshots to show it and explain it AGAIN.

Screenshots:

1. Serverstartup:

http://puu.sh/gJafW/a5239b7248.jpg

2. Servermapchange:

http://puu.sh/gJa3X/278bd16633.jpg

My problem:
The translation of DarkRP via the DarkRPModification Addon doesnt take effect on Serverstartup.
However it only happens on my linux dedicated server.
After a mapchange it works perfectly. 
Without a mapchange everything is in english with a exception of 10-20 things.
I removed my whole addons folder alot times to see if its my addons causing the error, but NO!

**Comment by FPtje** [comment]
Cannot reproduce, neither on listen nor dedicated server.

**Comment by FPtje** [comment]
![2015-03-21_10-32-15](https://cloud.githubusercontent.com/assets/1202014/6764556/91a2aaf6-cfb5-11e4-9a0a-bbb24d60867b.png)
That is on a dedicated server that just started, with `gmod_langauge` set to `bg` and the language file also set to `bg`

**Comment by deinemudda32** [comment]
I could send my language file and you could tell me whats wrong. I didnt find anything for hours.
https://www.dropbox.com/s/3ixu7f4ghmkuyio/german.lua?dl=0

**Comment by FPtje** [comment]
not a help forum.

2015-03-21 10:35 GMT+01:00 deinemudda32 <notifications@github.com>:

**Comment by deinemudda32** [comment]
I just wanted to show that I didnt make any mistakes but okay.

**Comment by FPtje** [comment]
Oh, your previous issue says Linux DS. I don't currently have a Linux DS, but it's a gmod bug if it happens on Linux only.

**Comment by deinemudda32** [comment]
yea but the chat commands works.

**Comment by deinemudda32** [comment]
Hey I just wanted to report something.
If I set the language code to "EN" then everything is german.
In server.cfg is gmod_language "de" defined but instead it runs the english translation.
