### ISSUE TITLE
Jobs are fully working in the F4 menu, but for some odd reason, Entities, Shipments and Ammo will not show up in the menu!

### ISSUE THREAD

**Issue by blackopscrazy0** [FPtje/darkrpmodification#65]
As I said the jobs work, but entities, shipments and ammo will not show up there, This only happened after Gmod update yesterday morning, the Entities can be spawned through direct command easily, and they work. The annoying bug makes it so that my players cant see the entities, shipments, and ammo. I checked up on console logs, no lua errors pertaining to anything... yet they still will not show up!

**Comment by FPtje** [comment]
Duplicate issue
