### ISSUE TITLE
F4 Menu

### ISSUE THREAD

**Issue by auskfc** [FPtje/darkrpmodification#77]
![image](https://cloud.githubusercontent.com/assets/15098492/10557687/d29a4900-7501-11e5-8dc7-ea43d5225d70.png)
How do I edit what is shown where the arrow is pointing?

http://imgur.com/wIlqwTR

**Comment by FPtje** [comment]
It uses the first model in the table.

**Comment by auskfc** [comment]
I have a working playermodel on my server when I change to it I can see it
but in f4 menu it comes up as a error

On Sat, Oct 17, 2015 at 9:37 PM, Falco Peijnenburg <notifications@github.com

**Comment by FPtje** [comment]
That's a shame to hear. Please head to the forums. forum.darkrp.com
