### ISSUE TITLE
"Weapons" tab disappears when default shipments are disabled

### ISSUE THREAD

**Issue by 2bdkid** [FPtje/darkrpmodification#80]
I'm disabling the default pistols because I want to replace them with M9K pistols

disabled_defaults.lua:
`DarkRP.disabledDefaults["shipments"] = {
["AK47"]         = true,
["Desert eagle"] = true,
["Fiveseven"]    = true,
["Glock"]        = true,
["M4"]           = true,
["Mac 10"]       = true,
["MP5"]          = true,
["P228"]         = true,
["Pump shotgun"] = true,
["Sniper rifle"] = true,
}`

I added custom guns to shipments.lua
`DarkRP.createShipment("M9K Desert Eagle", {
    model = "models/weapons/w_tcom_deagle.mdl",
    entity = "m9k_deagle",
    price = 400,
    amount = 1,
    separate = true,
    pricesep = 400,
    noship = true,
    allowed = {TEAM_GUN},
    category = "Pistols",
})`

`DarkRP.createShipment("M9K Glock", {
    model = "models/weapons/w_dmg_glock.mdl",
    entity = "m9k_glock",
    price = 350,
    amount = 1,
    separate = true,
    pricesep = 350,
    noship = true,
    allowed = {TEAM_GUN},
    category = "Pistols",
})`

`DarkRP.createShipment("M9K Sig P229R", {
    model = "models/weapons/w_sig_229r.mdl",
    entity = "m9k_sig_p229r",
    price = 300,
    amount = 1,
    separate = true,
    pricesep = 300,
    noship = true,
    allowed = {TEAM_GUN},
    category = "Pistols",
})`

![gmod](https://cloud.githubusercontent.com/assets/6799602/13053079/84046c2a-d3d0-11e5-91bd-f04f16403dbf.PNG)

When I enable at least one of the default weapons, the tab comes back.

`DarkRP.disabledDefaults["shipments"] = {
	["AK47"]         = true,
	["Desert eagle"] = true,
	["Fiveseven"]    = true,
	["Glock"]        = true,
	["M4"]           = true,
	["Mac 10"]       = true,
	["MP5"]          = true,
	["P228"]         = false,
	["Pump shotgun"] = true,
	["Sniper rifle"] = true,
}`

![gmod2](https://cloud.githubusercontent.com/assets/6799602/13053148/efe8e146-d3d0-11e5-89d6-616957561d28.PNG)

**Comment by 2bdkid** [comment]
If you would like to view my config files I pushed them to my github page: https://github.com/2bdkid/DarkRP-Modification-Config

**Comment by FPtje** [comment]
![weapons](https://cloud.githubusercontent.com/assets/1202014/13124718/0480e66a-d5c2-11e5-8ab8-88bccc24186e.png)

Works for me.
disabled_defaults:
```lua
DarkRP.disabledDefaults["shipments"] = {
	["AK47"]         = true,
	["Desert eagle"] = true,
	["Fiveseven"]    = true,
	["Glock"]        = true,
	["M4"]           = true,
	["Mac 10"]       = true,
	["MP5"]          = true,
	["P228"]         = true,
	["Pump shotgun"] = true,
	["Sniper rifle"] = true,
}
```

shipments.lua:
```lua
DarkRP.createShipment("Custom ~ Fiveseven", {
    model = "models/weapons/w_pist_fiveseven.mdl",
    entity = "weapon_fiveseven2",
    price = 0,
    amount = 10,
    separate = true,
    pricesep = 205,
    noship = true,
    allowed = {TEAM_GUN},
    category = "Pistols",
})


DarkRP.createShipment("Custom ~ AK47", {
    model = "models/weapons/w_rif_ak47.mdl",
    entity = "weapon_ak472",
    price = 2450,
    amount = 10,
    separate = false,
    pricesep = nil,
    noship = false,
    allowed = {TEAM_GUN},
    category = "Rifles",
})
```

My settings are also practically the same, I've tried with and without `restrictbuypistol`.

I'm sorry, I don't know what causes your issue and I cannot investigate it. Can you try to find out what's causing it? Keep me up to date in this issue.

**Comment by 2bdkid** [comment]
I tried manually installing DarkRP (2.6.2) but it didn't help. Could you try copying my darkrpmodification files and see if you get the same issue?

**Comment by FPtje** [comment]
I guess I could

**Comment by FPtje** [comment]
Can you link me to the exact workshop pages of those m9k weapons?

**Comment by 2bdkid** [comment]
This is the collection I'm using. http://steamcommunity.com/sharedfiles/filedetails/?id=623559708

**Comment by FPtje** [comment]
Well I don't know why it happened with your config, but not with mine. Either way I'm glad I tested your config. I found the issue. It's fixed in the latest version of DarkRP.

**Comment by 2bdkid** [comment]
Cool! Thanks alot
