### ISSUE TITLE
REQUEST: Allow disabling of default categories

### ISSUE THREAD

**Issue by BTone** [FPtje/darkrpmodification#81]
Really only want to override the canSee field of certain categories, but there doesn't seem to be a way to do that. Would it be possible to add categories in disableddefaults?

**Comment by FPtje** [comment]
Can't you recreate the category with the same name but different canSee?

Removing categories will cause default shipments not to be in any category. That will cause errors.

**Comment by MuteTM** [comment]
Is it possible to hide default categories automatically if they're empty?

**Comment by FPtje** [comment]
They should already be hidden

**Comment by MuteTM** [comment]
![related](http://i.imgur.com/5OmIxlN.png)
[Entities and Categories (DarkRPMod)](https://ghostbin.com/paste/tm5tx)

**Comment by FPtje** [comment]
Cannot reproduce with your entities and categories.

![2016-04-26_17-36-58](https://cloud.githubusercontent.com/assets/1202014/14824229/8ceea3c2-0bd5-11e6-9d3a-cc9578523a1f.jpg)

**Comment by MuteTM** [comment]
E-mailed you a copy of my darkrpmodification, just commenting here in case it landed in the spam box.

**Comment by FPtje** [comment]
It did end up in my spam box.
