### ISSUE TITLE
weapon_ak47custom throws this error.

### ISSUE THREAD

**Issue by MaDmaxwell311** [FPtje/darkrpmodification#82]
Description of the bug
On Load up I get a console error.

How to make the bug happen
Load up the server.

Lua errors
SWEP (weapon_ak47custom) is derived from non existant SWEP (weapon_cs_base2) - Expect errors!

Why the developer of DarkRP is responsible for this issue
He is responsible because, I have edited 0 files, I get no other issues and this error has only started to occur when I updated to latest DarkRP

**Comment by FPtje** [comment]
Works for me. Make sure DarkRP is installed properly.

**Comment by MaDmaxwell311** [comment]
Double checked, for some reason a hell of a lot of my files for my test server (the server that I found the bug on) had been corrupted. Sorry for the confusion.

**Comment by FPtje** [comment]
Do you use filezilla?

**Comment by MaDmaxwell311** [comment]
Yes, but not for my test server. My test server is hosted on a second desktop pc and the corrupted files were caused by my HDD was failing.

**Comment by FPtje** [comment]
Ah, ok. Thanks.
