### ISSUE TITLE
Memory leak in MySQLOO

### ISSUE THREAD

**Issue by MrMomox** [FPtje/darkrpmodification#84]
Hello,
I just read the "\lua\darkrp_config\mysql.lua"
```
--[[
MANUAL!
HOW TO USE MySQL FOR DARKRP!
Download andyvincent's/Drakehawke's/KingofBeast's gm_MySQL OO module and read the guide here:
http://facepunch.com/showthread.php?t=1357773
]]
```
and you should probably recommend users to use tmysql4 instead of mysqloo.
The problem with mysqloo:
1.  the memory leak (> "Objects created in mysql::query commands will not be carbage collected" - facepunch forum)
2. Hasn't been updated for a long time

Greetings,
Momox

**Comment by Bo98** [comment]
MySQLOO has been updated by others. That link is outdated and the latest version can be found at https://facepunch.com/showthread.php?t=1515853 which should no longer have a memory leak.

That said, tmysql4 is supported so should be mentioned in the config.
