### ISSUE TITLE
CP issues

### ISSUE THREAD

**Issue by Tendersexpartner** [FPtje/darkrpmodification#85]
Hi im trying to set the cp's but i keep getting this error

[ERROR] addons/darkrpmodification-master/lua/darkrp_customthings/jobs.lua:42: table index is nil
  1. unknown - addons/darkrpmodification-master/lua/darkrp_customthings/jobs.lua:42
   2. doInclude - [C]:-1
    3. loadCustomDarkRPItems - gamemodes/methrp/gamemode/libraries/modificationloader.lua:137
     4. Call - gamemodes/methrp/gamemode/libraries/modificationloader.lua:148
      5. unknown - gamemodes/methrp/gamemode/cl_init.lua:53
 

this is what my cp's look like 

GAMEMODE.CivilProtection = {
	[TEAM_POLICE] = true,
	[TEAM_CHIEF] = true,
	[TEAM_MAYOR] = true,
	[TEAM_SWAT] = true,
}

is there something im doing wrong? because the swat job is in there

**Comment by FPtje** [comment]
Not a help forum.
