### ISSUE TITLE
Disable the door system

### ISSUE THREAD

**Issue by AnthonyFuller** [FPtje/darkrpmodification#87]
I know their used to be a option in darkrp modification to remove the door system now i cant find it

**Comment by FPtje** [comment]
I'm not going to look for it for you.

**Comment by AnthonyFuller** [comment]
No
What can I do to disable it?

**Comment by AnthonyFuller** [comment]
I know http://corefiles.darkrp.eu BUT do I delete the module from the gamemode folder

**Comment by FPtje** [comment]
check out disabled_defaults, go to forum.darkrp.com if you can't find it there.
