### ISSUE TITLE
drop money on death is broke

### ISSUE THREAD

**Issue by JackPlaysGames** [FPtje/darkrpmodification#88]
Hello. drop money on death is set to false and deathfee is set to 0. but then my players still drop the money. please fix this because they drop all there money. or maybe there is another way to disable it?

**Comment by FPtje** [comment]
Must be some addon doing it.

**Comment by JackPlaysGames** [comment]
i have no other addons to do this. i just have player model ones

**Comment by FPtje** [comment]
When I die I don't drop money. That means you're doing something different.
