### ISSUE TITLE
Interesting issue when it comes to shipments. 

### ISSUE THREAD

**Issue by Servius** [FPtje/darkrpmodification#90]
Many DarkRP servers over time face several trivial issues that players like to focus REALLY hard on when they are really only, well, trivial. Some issues are levels, sever economies, staffing, etc. While working on an overhaul on our weapons system I decided to avoid erasing player inventories by creating variants to use the new stats and prices laid out in our overhaul. I thought this would save time since I could just go through to the old shipment codes and just swap out the shipment id to the new variant ie darkrp_ak47 ->darkrp_ak47_variant but what ended up happening was everyones shipments ended up getting swapped over to a random swep on the server. Some people had 300 shotguns in their inventory and when the shipment code switched they ended up with 300 sound sweps stacked into each other (and many more ridiculous situations) 

What Ive tried so far is reverting one of the changed shipments back to the og id ie darkrp_ak47_variant -> darkrp_ak47 and the weapons swapped back to their form which is fine...I guess. Now I could go through and revert them all and then just write new shipment code for all the variants and just call it a done day but there is still **one issue left** I dont want to sell the og weapons on either one of my dealers. Is there a way to have the shipment code be there but not be sold? Thank you for reading.

**Comment by Servius** [comment]
I wont say Ive searched every corner of the galaxy for a solution to this but I have done a fair amount of checking. Just looking for a "Is_Sold = False" function to tag onto these things.

**Comment by FPtje** [comment]
Ask the authors of your dealer and inventory addons. I don't own those, so I can't influence their behaviour.

**Comment by Servius** [comment]
Not looking for you to influence the behavior of other addons. My "dealer" addon is just a gun dealer and black market dealer job on DarkRP and its the removal of old shipments that caused the problem, not the handling of the situation via the inventory addon. The ability to disable shipments without commenting them out seems to be fairly simple functionality that could be expanded upon over time. Like a built "in sell and display only if <usergroup/job/team/permission/playermodel/cooljoke/command/etc.> = true" 

or even the ability to do allowed = { nil }, to make it so the shipment is present but not being sold. Could be useful in spawning in pre-made shipments to make sure everything is working in terms of ammo count, model, etc. 

You already have a couple things that are pointed to the more specific situations like onBought or getPrice. In my opinion something like the above would have at least some relative use compared to some other suggestions made in the past.

**Comment by FPtje** [comment]
You can make them invisible and unbuyable with the existing options. There's no need for me to make another option for things you can already do. Especially since you only want it because your inventory addon has some weird behaviour.

**Comment by Servius** [comment]
Could you pretty please show me what Id have to do to make it work with the existing options? An example if possible.

**Comment by FPtje** [comment]
http://wiki.darkrp.com/index.php/DarkRP:CustomShipmentFields

Setting `customCheck` to `function() return false` end should probably do the trick, depending on the F4 menu and settings you use.

**Comment by Servius** [comment]
Alrighty. Thank you.
